name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      env:
        MY_DATOMIC_USERNAME: ${{ secrets.MY_DATOMIC_USERNAME.MY_DATOMIC_USERNAME }}
        MY_DATOMIC_PASSWORD: ${{ secrets.MY_DATOMIC_PASSWORD.MY_DATOMIC_PASSWORD}}
      run: | 
            echo "This is a secret value: $MY_DATOMIC_USERNAME"
            echo "This is a secret value: $MY_DATOMIC_PASSWORD"
    - name: Run tests
      run: lein test
